name: Praneeth
title: Saipraneeth Devunuri
email: devunurisaipraneeth@gmail.com
github_username: saipran7777
linkedin_username: devunuri-sai-praneeth-0b1987b8
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
facebook_username: praneethDevunuri
