name: Praneeth
title: Saipraneeth Devunuri
email: devunurisaipraneeth@gmail.com
github_username: saipraneethd
linkedin_username: saipraneethd
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
facebook_username: praneethDevunuri
